### ISSUE TITLE
Wiris vs. advanced forum

### ISSUE THREAD

**Issue by neeesn** [wiris/moodle-atto_wiris#23] opened 2018-01-19 07:56 UTC
Hi,
We have a moodle page in version 3.1.4.
We have the problem that formulars inserted via the Math Editor in Advanced forum replys are being removed when saved. Theres no problem in the ordinary forum posts. ?

**Comment by manuelwiris** [comment] 2018-01-23 15:11
@neeesn 

Thanks for your feedback. 

We are able to reproduce the issue in our end. 

WIRIS Plugin uses a intermediate codification to save MathML into Moodle database. The reason is because MathML (despite of is a W3C specification) is cleaned by Moodle.

Seems that the Advanced Forum saves directly the MathML.  As soon the bug is fixed we will back to you.

Best,

**Comment by neeesn** [comment] 2018-01-24 23:20
Hi
It seems to be a known issue that advanced forum strips HTML in earlier versions ( such as ours 3.1.4). It should be fixed in later versions of Moodle. I will test when we update.

**Comment by manuelwiris** [comment] 2018-03-06 15:45
@neeesn Thanks for your feedback.

I will close the issue. Please don't hesitate to come back if you have any problem

**Closed by manuelwiris** 2018-03-06 15:45 UTC
