### ISSUE TITLE
atto wiris buttons do not work with multilang2

### ISSUE THREAD

**Issue by cvuva** [wiris/moodle-atto_wiris#72] opened 2021-03-19 14:22 UTC
Hi, 

I recently updated my moodle 3.6.10 adding the atto multilang2 filter and plugin and proceeded to update the wiris filter (7.24.0, 2020090300) and atto plugin (7.24.0, 2020090300) to the latest version.

Since the installation of multilang2 within the atto editor, the two wiris math and chemistry atto buttons have stopped working.

The error that I get in the browser console is the following but I don't copy everything so as not to extend unnecessarily:

Uncaught ReferenceError: WirisPlugin is not defined
    updateOriginal https://moodle2017-des.uva.es/theme/yui_combo.php?3.17.2/array-extras/array-extras.js&m/1616147229/atto_equation/button/button-debug.js&m/1616147229/atto_charmap/button/button-debug.js&m/1616147229/atto_table/button/button-debug.js&m/1616147229/atto_wiris/button/button-debug.js&m/1616147229/atto_undo/button/button-debug.js&m/1616147229/atto_accessibilitychecker/button/button-debug.js&m/1616147229/atto_accessibilityhelper/button/button-debug.js&m/1616147229/atto_multilang2/button/button-debug.js&3.17.2/promise/promise.js&m/1616147229/atto_html/beautify/beautify-debug.js&m/1616147229/atto_html/codemirror/codemirror-debug.js&m/1616147229/atto_html/button/button-debug.js:3378
    updateOriginal https://moodle2017-des.uva.es/theme/yui_combo.php?3.17.2/array-extras/array-extras.js&m/1616147229/atto_equation/button/button-debug.js&m/1616147229/atto_charmap/button/button-debug.js&m/1616147229/atto_table/button/button-debug.js&m/1616147229/atto_wiris/button/button-debug.js&m/1616147229/atto_undo/button/button-debug.js&m/1616147229/atto_accessibilitychecker/button/button-debug.js&m/1616147229/atto_accessibilityhelper/button/button-debug.js&m/1616147229/atto_multilang2/button/button-debug.js&3.17.2/promise/promise.js&m/1616147229/atto_html/beautify/beautify-debug.js&m/1616147229/atto_html/codemirror/codemirror-debug.js&m/1616147229/atto_html/button/button-debug.js:4561
    setupSelectionWatchers https://moodle2017-des.uva.es/theme/yui_combo.php?m/1616147229/editor_atto/rangy/rangy-debug.js&3.17.2/handlebars-base/handlebars-base.js&3.17.2/handlebars-compiler/handlebars-compiler.js&m/1616147229/core/handlebars/handlebars-debug.js&3.17.2/timers/timers.js&3.17.2/querystring-stringify/querystring-stringify.js&m/1616147229/editor_atto/editor/editor-debug.js&m/1616147229/editor_atto/menu/menu-debug.js&m/1616147229/editor_atto/plugin/plugin-debug.js&m/1616147229/atto_collapse/button/button-debug.js&m/1616147229/atto_fullscreen/button/button-debug.js&m/1616147229/atto_title/button/button-debug.js&m/1616147229/atto_bold/button/button-debug.js&m/1616147229/atto_italic/button/button-debug.js&m/1616147229/atto_unorderedlist/button/button-debug.js&m/1616147229/atto_orderedlist/button/button-debug.js&m/1616147229/atto_link/button/button-debug.js&m/1616147229/atto_teamsmeeting/button/button-debug.js&m/1616147229/atto_image/button/button-debug.js&m/1616147229/atto_media/button/button-debug.js:13228
    _notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13680
    notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13709
    _notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13372
    _procSubs https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13498
    fireSimple https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13465
    _fire https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13447
    fire https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13416
    fire https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:30549
    _notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:31985
    _proxy https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:31903
    _notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13680
    notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13709
    _notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13372
    _procSubs https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13498
    fireSimple https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13465
    _fire https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13447
    fire https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13416
    fn https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:20467
    focus https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:19529
    _toggle https://moodle2017-des.uva.es/theme/yui_combo.php?m/1616147229/editor_atto/rangy/rangy-debug.js&3.17.2/handlebars-base/handlebars-base.js&3.17.2/handlebars-compiler/handlebars-compiler.js&m/1616147229/core/handlebars/handlebars-debug.js&3.17.2/timers/timers.js&3.17.2/querystring-stringify/querystring-stringify.js&m/1616147229/editor_atto/editor/editor-debug.js&m/1616147229/editor_atto/menu/menu-debug.js&m/1616147229/editor_atto/plugin/plugin-debug.js&m/1616147229/atto_collapse/button/button-debug.js&m/1616147229/atto_fullscreen/button/button-debug.js&m/1616147229/atto_title/button/button-debug.js&m/1616147229/atto_bold/button/button-debug.js&m/1616147229/atto_italic/button/button-debug.js&m/1616147229/atto_unorderedlist/button/button-debug.js&m/1616147229/atto_orderedlist/button/button-debug.js&m/1616147229/atto_link/button/button-debug.js&m/1616147229/atto_teamsmeeting/button/button-debug.js&m/1616147229/atto_image/button/button-debug.js&m/1616147229/atto_media/button/button-debug.js:15502
    _callbackWrapper https://moodle2017-des.uva.es/theme/yui_combo.php?m/1616147229/editor_atto/rangy/rangy-debug.js&3.17.2/handlebars-base/handlebars-base.js&3.17.2/handlebars-compiler/handlebars-compiler.js&m/1616147229/core/handlebars/handlebars-debug.js&3.17.2/timers/timers.js&3.17.2/querystring-stringify/querystring-stringify.js&m/1616147229/editor_atto/editor/editor-debug.js&m/1616147229/editor_atto/menu/menu-debug.js&m/1616147229/editor_atto/plugin/plugin-debug.js&m/1616147229/atto_collapse/button/button-debug.js&m/1616147229/atto_fullscreen/button/button-debug.js&m/1616147229/atto_title/button/button-debug.js&m/1616147229/atto_bold/button/button-debug.js&m/1616147229/atto_italic/button/button-debug.js&m/1616147229/atto_unorderedlist/button/button-debug.js&m/1616147229/atto_orderedlist/button/button-debug.js&m/1616147229/atto_link/button/button-debug.js&m/1616147229/atto_teamsmeeting/button/button-debug.js&m/1616147229/atto_image/button/button-debug.js&m/1616147229/atto_media/button/button-debug.js:15006
    rbind https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:12362
    notifySub https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:21930
    notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13709
    _notify https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13372
    _procSubs https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13498
    fireSimple https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13465
    _fire https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13447
    fire https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13416
    fn https://moodle2017-des.uva.es/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:20467
yui_combo.php:3378:25

Thanks,

**Comment by dcanetma** [comment] 2021-03-22 08:17
Thanks for reporting.

We'd need to reproduce your issue in order to fix it.

Would you be so kind to inform of the versions you're using of?
- Moodle
- multilang2

Is there any configuration on multilang2 that we'd need to be aware of?

Thanks.

**Comment by dcanetma** [comment] 2021-03-22 08:30
Also, if you'd be so kind to indicate if there are any steps necessary to reproduce the issue.

That will also be very helpful.

Thanks

**Comment by cvuva** [comment] 2021-03-22 08:37
Moodle:
$version  = 2018120310.00;
$release  = '3.6.10 (Build: 20200511)'; 

Multilang2:
atto-plugin: 
$plugin->version      = 2019112700; 
$plugin->release      = 'master - Release v1.11.2 (Build 2019112700) for Moodle 3.6, 3.7 and 3.8';
$plugin->dependencies = array(
    'filter_multilang2' => 2019111900 // The filter_multilang2 must be present (any version).
);

Filter: 
$plugin->version   = 2020101300;
$plugin->release   = '1.1.2';

To reproduce the problem configure in atto bar:
math = wiris
other = multilang2, html
Then go to create a label in any course and click on any of the two wiris buttons (mathematics, chemistry) and the expression editor for both is not shown.

**Comment by juacas** [comment] 2021-03-22 10:40
Hello, I've traced the problem down to the following code fragment:

// Override updateOriginal to update the content of the text area element.
        host._wirisupdateOriginal = host.updateOriginal;
        host.updateOriginal = function() {
            host._wirisupdateOriginal();
            var html = host.textarea.get('value');
            var value = WirisPlugin.Parser.endParse(html);
            value = _convertSafeMathML(value);
            host.textarea.set('value', value);
        };

it seems that atto_wiris_button overrides _updateOriginal_ but does not load its main javascript in the proper order.
Multilang2 filter updates the content of the editor to format the languages and triggers an event for the rest of the components.
When atto_wiris_button executes the listener  the /lib/editor/atto/plugins/wiris/core.js library is not loaded at this moment.

**Comment by dcanetma** [comment] 2021-03-23 10:17
Hi, @cvuva @juacas 

This information will very useful to try to reproduce the issue.

We'll try to fix it our next release.

Keep you posted.

Many thanks for your feedback.

**Comment by juacas** [comment] 2021-03-23 16:37
We'll be looking forward the fix! This is currently a big big stopper for our 30 000 users!

**Comment by juacas** [comment] 2021-05-09 15:52
Is there any progress with this issue? This is a serious blocker for the use of Wiris in our University.

**Comment by juacas** [comment] 2021-05-12 12:20
Workaround for this issue:
Lines 254-262 of button.js

```
        host.updateOriginal = function() {
            host._wirisupdateOriginal();
            setTimeout(() => {
                var html = host.textarea.get('value');
                var value = WirisPlugin.Parser.endParse(html);
                value = _convertSafeMathML(value);
                host.textarea.set('value', value);
            }, 300);
        };
```

This patch defers the processing of the textarea until the next cycle of the event loop.
However, this is an ugly hack that hide the root of the problem that seems to be related to the proper loading of dependencies.

I hope this helps.

**Comment by dcanetma** [comment] 2021-05-12 13:41
Many thanks for the patch, @juacas 

Totally agree. 
Certainly, this patch will mitigate the issue but can't be considered a final solution.

In any case, I'd like to inform you that we've given high priority to this issue and we're currently working on the fix.

Also, I take the chance to thank for your patience on this matter. 

I'm sorry for the inconveniences it may caused.

Keep you posted.

**Comment by dcanetma** [comment] 2021-05-13 15:48
Hi, @cvuva @juacas

I fix for this issue is available to download from [the main branch of this repository](https://github.com/wiris/moodle-atto_wiris/tree/main).

We've prepared an [Acceptance test](https://drive.google.com/file/d/1Luc8-UgRpgkk8o-FR6AaI14kpf58Pyxa/view?usp=sharing) to validate that the issue is fixed.

More information on the pull request #74

**Comment by dcanetma** [comment] 2021-05-13 15:49
This fix will be available on the next release planned between 14th and 17th of may.

**Comment by cvuva** [comment] 2021-06-14 07:43
We are migrating the moodle version from 3.6 to 3.10 ($ release = '3.10.4+ (Build: 20210527)') and from php 7.2 to 7.3.28 and this bug between wiris buttons (mathematical, chemical) for atto editor and multilang2 reappears.

The version of the wiris plugin for atto has not been changed:
$ plugin-> version = 2021050600;
$ plugin-> release = '7.26.0';

The wiris filter version has not been changed:
$ plugin-> version = 2021050600;
$ plugin-> release = '7.26.0';
$ plugin-> requires = 2011120511;
$ plugin-> maturity = MATURITY_STABLE;
$ plugin-> component = 'filter_wiris';


Neither the atto plugin nor the multilang2 filter has been changed:

$ plugin-> version = 2019112700; // The current plugin version (Date: YYYYMMDDXX).
$ plugin-> release = 'master - Release v1.11.2 (Build 2019112700) for Moodle 3.6, 3.7 and 3.8';

$ plugin-> version = 2020101300; // The current plugin version (Date: YYYYMMDDXX).
$ plugin-> requires = 2013111800; // Requires this Moodle version.
$ plugin-> component = 'filter_multilang2'; // Full name of the plugin (used for diagnostics).
$ plugin-> release = '1.1.2';

**Comment by dcanet-at-wiris** [comment] 2021-07-02 11:13
Hi @cvuva 

Have you tried run the test we recently added to validate this issue?

> The file is this one [tests/behat/atto_pluginCompatibility_multilang2.featur_](https://github.com/wiris/moodle-atto_wiris/blob/stable/tests/behat/atto_pluginCompatibility_multilang2.featur_)

In order to run this test, you will need to rename the file first to `atto_pluginCompatibility_multilang2.feature`.

> Unfortunately, we did not manage to add third-party plugin compatibility tests to the behat suite, for both local and on CI environments, without affecting [the current strategy Moodle test strategy we're using](https://github.com/moodlehq/moodle-docker#use-containers-for-running-behat-tests).  
> We didn't find a way that the included specifications for optional third-party plugins installed (like Multilang2, Image2,  ..) on the behat test suite work on the build machine(GitHub Actions). 

Also, If you could provide a screen recording or snapshot, it would be very useful.

Thanks for reporting.

**Comment by cvuva** [comment] 2021-07-05 07:06
Hi,

I updated some moodle plugins and the core version and it started working again. The wiris expression buttons for atto have worked without a problem since then.

Thanks.

**Comment by dcanet-at-wiris** [comment] 2021-07-05 07:09
This is good news.

Thanks for reporting it, @cvuva 

Kind regards.

**Closed by dcanet-at-wiris** 2021-07-05 07:09 UTC
Labels: state:accepted, state:requested, type:bug
