### ISSUE TITLE
Unable edit text when atto editor open in moodle

### ISSUE THREAD

**Issue by AviMoto** [wiris/moodle-atto_wiris#76] opened 2021-06-01 22:34 UTC
When atto editor open in modal and then try to open the wiris editor, the wiris editor is not writable by keyboard and only the wiris button and freehand write work

**Comment by nadavkav** [comment] 2021-06-02 05:34
We are experiencing this too, so please consider fixing it.

**Comment by dcanet-at-wiris** [comment] 2021-06-25 11:49
Hola @AviMoto 

Thanks for reporting the issue.

Would you be so kind to indicate how to open the Atto editor in _'modal'_ mode?
I've been unable to find any documentation online about how to activate it, any plugin option or initialization command.

We'll try to reproduce the issue, so we can find a fix for it. 

Kind regards,

**Comment by dcanet-at-wiris** [comment] 2021-07-02 11:28
Hola @AviMoto 
Any news?

**Comment by nadavkav** [comment] 2021-07-02 14:32
Here is as eample of the situation:
1. A teacher open a student PDF submission inside an assignment grading page
2. Click the "Atto editor comments" button (on the PDF editor toolbar, far right)
3. After the Atto editor is open, teacher clicks the MathType button
See attached screen capture
![image](https://user-images.githubusercontent.com/231168/124289680-4325f500-db5b-11eb-8b90-4b4bf67d3ea4.png)
Before @AviMoto 's fix, teacher can not get keyboard focus or input into the MathType dialog.
After Avi's fix, teacher can input via keyboard into the MathType dialog.

**Comment by dcanet-at-wiris** [comment] 2021-07-05 06:59
Many thanks for the information, @nadavkav

**Comment by AviMoto** [comment] 2021-08-16 12:56
Hi @dcanet-at-wiris ,
Do you have estimmation when You will release a fix?

**Comment by icaparros-at-wiris** [comment] 2022-01-05 11:12
Thanks for the information @nadavkav

Unfortunately, I’m unable to reproduce the bug myself. Would you provide some information that could help me?

- Which moodle version are you using?
- The “Atto editor comments” button is next to the stamp cross button?
- There is some moodle configuration that I should to modify to reproduce this issue?

Also, will be so useful if you could add some video/gif reproducing the bug.

Kind regards,

**Comment by icaparros-at-wiris** [comment] 2022-01-13 15:38
I proceed to close the issue. Do not hesitate to reopen a new issue in the future.

**Closed by icaparros-at-wiris** 2022-01-13 15:38 UTC
Labels: type:bug, state:accepted
