### ISSUE TITLE
bug with IE 11

### ISSUE THREAD

**Issue by birdy4012** [wiris/moodle-atto_wiris#52] opened 2019-05-31 19:24 UTC
hi,
we've a issu with IE 11. Do you have the same thing ?
![image](https://user-images.githubusercontent.com/9442042/58727885-8e391100-83b3-11e9-9080-3be71f1d2f33.png)
_(sorry, screenshot is in french)_
After that, the javascript is crashed, and the follow block (like file upload block in course parameter page) doesn't work.
I know IE11 is not the best browser.. but our teachers have their habit

**Comment by manuelwiris** [comment] 2019-06-03 07:37
Hi @birdy4012 

This issue is a duplicate of #49. 

Best,

**Closed by manuelwiris** 2019-06-03 07:37 UTC

**Comment by pmatabiau** [comment] 2019-06-04 18:10
oops sorry, I haven't saw it.
If this can help you, Wiris 7.9 works fine, but 7.12, 7.13 don't work with IE11 (we've uninstall and install previous versions of filter+atto from your git tags)

**Comment by merrill-oakland** [comment] 2019-10-03 14:26
As and FYI, this appears to be fixed in 7.16.0 and up.
